exclude: '((generator.py)|(generated/.*))$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer

  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.3
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 19.10b0
          - usort == 1.0.2

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config=setup.cfg]
        exclude: generator.py

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format