name: ComfyUI Workflows Test

on:
  push:
    branches:
      - main
      - add_comfyui_workflow_ci
  workflow_dispatch: 

env:
  SELENIUM_CONTAINER_NAME: ci-selenium-30m
  SELENIUM_IMAGE: selenium/standalone-chrome:119.0-chromedriver-119.0-grid-4.15.0-20231129
  COMFYUI_CONTAINER_NAME: ci-comfyui-30m
  COMFYUI_IMAGE: registry.cn-beijing.aliyuncs.com/oneflow/comfyui-onediff:ci-oneflow-f699e4ba3-20231201
  SDXL_BASE: /share_nfs/hf_models/sd_xl_base_1.0.safetensors
  UNET_INT8: /share_nfs/hf_models/unet_int8

jobs:
  selenium-test:
    runs-on: [self-hosted, gpu]

    steps:
      - name: Start Selenium container
        run: |
          docker rm -f ${{ env.SELENIUM_CONTAINER_NAME }} || true
          docker pull ${{ env.SELENIUM_IMAGE }}
          docker run --network host \
            --shm-size="2g" --rm --name ${{ env.SELENIUM_CONTAINER_NAME }} \
            -d $SELENIUM_IMAGE sleep 1800
          docker exec ${{ env.SELENIUM_CONTAINER_NAME }} /opt/bin/entry_point.sh&

      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout ComfyUI
        uses: actions/checkout@v2
        with:
          repository: comfyanonymous/ComfyUI
          path: ComfyUI

      - name: Checkout ConfyUI Speedup Nodes
        uses: actions/checkout@v2
        if: ${{ inputs.is_priv }}
        with:
          ref: ${{ inputs.branch }}
          repository: ${{ secrets.ONEFLOW_PRIV_ORG }}/comfyui-speedup
          token: ${{ secrets.ONEFLOW_PRIV_GH_TOKEN }}
          path: comfyui-speedup

      - name: Start ComfyUI container
        run: |
          docker rm -f ${{ env.COMFYUI_CONTAINER_NAME }} || true
          docker pull ${{ env.COMFYUI_IMAGE }}
          docker run -it --shm-size=8G -P --privileged --runtime=nvidia --rm \
              --gpus all --network host --name ${{ env.COMFYUI_CONTAINER_NAME }} \
              -v `pwd`/ComfyUI:/app/ComfyUI \
              -v `pwd`/comfyui-speedup:/app/ComfyUI/custom_nodes/comfyui-speedup \
              -v ${{ env.SDXL_BASE }}:/app/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors:ro \
              -v ${{ env.UNET_INT8 }}:/app/ComfyUI/models/unet_int8/unet_int8:ro \
              -w /app \
              -d ${{ env.COMFYUI_IMAGE }} sleep 1800
          docker exec ${{ env.COMFYUI_CONTAINER_NAME }} python /app/ComfyUI/main.py --port 8855&

      - name: Wait for container to start
        run: sleep 5

      - name: Run Tests
        run: |
          pip install -r requirements.txt
          python test_by_ui.py --workflow workflows/sdxl-unet-speedup-graph-saver.json
        working-directory: tests/comfyui 
