name: Run examples

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "**/*.md"
      - "LICENSE*"
env:
  CONTAINER_NAME: onediff-test
  REGION_ID: cn-beijing
  ACR_ORG: registry.cn-beijing.aliyuncs.com/oneflow
  COMFYUI_SRC_DIR: ComfyUI
  COMFYUI_SPEEDUP_DIR: comfyui-speedup
  SDXL_BASE: /share_nfs/hf_models/sd_xl_base_1.0.safetensors
  UNET_INT8: /share_nfs/hf_models/unet_int8
  SELENIUM_CONTAINER_NAME: ci-selenium-90m
  SELENIUM_IMAGE: registry.cn-beijing.aliyuncs.com/oneflow/standalone-chrome:119.0-chromedriver-119.0-grid-4.15.0-20231129
concurrency:
  group: sd-examples-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-examples:
    name: " ${{ matrix.test-suite }} ${{ matrix.image }}"
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        image:
          - onediff:cu118
          - onediff-pro:cu121
        test-suite:
          - diffusers_examples
          - comfy
    steps:
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Fix permissions
        run: |
          set -x
          docker run --rm -v $PWD:$PWD -w $PWD busybox rm -rf *
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout ComfyUI
        if: matrix.test-suite == 'comfy'
        uses: actions/checkout@v2
        with:
          repository: comfyanonymous/ComfyUI
          path: ${{ env.COMFYUI_SRC_DIR }}
      - name: Checkout ConfyUI Speedup Nodes
        uses: actions/checkout@v2
        if: matrix.test-suite == 'comfy'
        with:
          repository: ${{ secrets.ONEFLOW_PRIV_ORG }}/comfyui-speedup
          token: ${{ secrets.ONEFLOW_PRIV_GH_TOKEN }}
          path: ${{ env.COMFYUI_SPEEDUP_DIR }}
      - name: Setup docker
        run: |
          docker rm -f ${{ env.SELENIUM_CONTAINER_NAME }} || true
          docker pull ${{ env.SELENIUM_IMAGE }}
          docker run --network host \
            --shm-size="2g" --rm --name ${{ env.SELENIUM_CONTAINER_NAME }} \
            -d ${{ env.SELENIUM_IMAGE }} sleep 5400
          docker exec ${{ env.SELENIUM_CONTAINER_NAME }} /opt/bin/entry_point.sh&
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.ACR_ORG }}/${{ matrix.image }}
          docker run --rm --gpus=all -d --privileged --shm-size=8g \
            --pids-limit 2000 \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            -v $HOME/test-container-cache-${{ env.CONTAINER_NAME }}/dot-local:/root/.local \
            -v $HOME/test-container-cache-${{ env.CONTAINER_NAME }}/dot-cache:/root/.cache \
            -v /share_nfs:/share_nfs:ro \
            -v ${PWD}/${{ env.COMFYUI_SRC_DIR }}:/app/ComfyUI \
            -v ${PWD}/${{ env.COMFYUI_SPEEDUP_DIR }}:/app/ComfyUI/custom_nodes/comfyui-speedup \
            -v ${{ env.SDXL_BASE }}:/app/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors:ro \
            -v ${{ env.UNET_INT8 }}:/app/ComfyUI/models/unet_int8/unet_int8:ro \
            -v $PWD:/src/onediff \
            -w /src/onediff \
            -e HF_HUB_OFFLINE=1 \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ env.ACR_ORG }}/${{ matrix.image }} \
            sleep 5400
      - run: nvidia-smi
      - run: nvidia-smi -L
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - if: matrix.test-suite == 'comfy'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 -m pip install -r tests/comfyui/requirements.txt --user
      - if: matrix.test-suite == 'comfy'
        run: docker exec -d ${{ env.CONTAINER_NAME }} python3 /app/ComfyUI/main.py --port 8855
      - if: matrix.test-suite == 'comfy'
        run: docker exec -w /src/onediff/tests/comfyui ${{ env.CONTAINER_NAME }} python3 test_by_ui.py --workflow workflows/sdxl-unet-speedup-graph-saver.json
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image.py --model_id=/share_nfs/hf_models/stable-diffusion-v1-5
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/image_to_image.py --model_id=/share_nfs/hf_models/stable-diffusion-2-1
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image_sdxl.py --base /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --compile_vae False --height 512 --width 512
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image_sdxl.py --base /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --compile_unet False --height 512 --width 512 --use_multiple_resolutions True
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image_controlnet.py --base=/share_nfs/hf_models/stable-diffusion-v1-5 --controlnet=/share_nfs/hf_models/sd-controlnet-canny --input_image=/share_nfs/hf_models/input_image_vermeer.png
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} python3 benchmarks/stable_diffusion_2_unet.py --model_id=/share_nfs/hf_models/stable-diffusion-2-1
      - if: matrix.test-suite == 'diffusers_examples'
        run: docker exec ${{ env.CONTAINER_NAME }} bash examples/unet_save_and_load.sh --model_id=/share_nfs/hf_models/stable-diffusion-2-1
